// ============================================================
// VERIFIED PORTFOLIO DATA — Hassan Mohammed Alghandour
// All content extracted from verified source documents only.
// NO fabricated information.
// ============================================================

export const personalInfo = {
  nameEn: "Hassan Alghandour",
  nameAr: "حسن محمد الغندور",
  nameRu: "Хасан Мухаммад Альгхандур",
  titleEn: "Mobile App Developer (Flutter)",
  titleAr: "مطوّر تطبيقات موبايل بتقنية Flutter",
  titleRu: "Разработчик мобильных приложений (Flutter)",
  locationEn: "Gaza, Palestine",
  locationAr: "غزة، فلسطين",
  locationRu: "Газа, Палестина",
  email: "hassanalghandour2002@gmail.com",
  phone: "(+972) 592261812",
  linkedin: "https://www.linkedin.com/in/hassanalghandour/",
  github: "https://github.com/hassanalghandourabuali",
  taglineEn: "I build mobile apps with Flutter, backed by an academic background in Electronic Business Management and hands-on experience managing social media pages.",
  taglineAr: "أطوّر تطبيقات موبايل باستخدام Flutter، بخلفية أكاديمية في إدارة الأعمال الإلكترونية وخبرة عملية في إدارة صفحات السوشيال ميديا.",
  taglineRu: "Я создаю мобильные приложения на Flutter, имею диплом по управлению электронным бизнесом и практический опыт в управлении страницами в соцсетях.",
};

export const summaryEn = `Electronic Business Management graduate with practical experience in customer service, sales, CRM systems, and customer data management within the telecommunications and technology sectors. Combines a strong business background with technical understanding, focusing on mobile application development using Flutter, customer experience (CX), and digital operations.`;

export const summaryAr = `خريج إدارة الأعمال الإلكترونية بخبرة عملية في خدمة العملاء والمبيعات وأنظمة CRM وإدارة بيانات العملاء في قطاعي الاتصالات والتكنولوجيا. يجمع بين خلفية أعمال قوية وفهم تقني، مع تركيز واضح على تطوير تطبيقات الموبايل باستخدام Flutter وتجربة العملاء والعمليات الرقمية.`;

export const summaryRu = `Выпускник по управлению электронным бизнесом с практическим опытом в обслуживании клиентов, продажах, CRM-системах и управлении данными клиентов в секторах телекоммуникаций и технологий. Сочетает сильную бизнес-базу с техническим пониманием, фокусируясь на разработке мобильных приложений с Flutter.`;

// ============================================================
// EXPERIENCE — verified from CV
// ============================================================
export const experiences = [
  {
    id: "developerplus",
    roleEn: "Mobile Application Developer Intern",
    roleAr: "متدرب تطوير تطبيقات موبايل",
    roleRu: "Стажёр по разработке мобильных приложений",
    orgEn: "Developer Plus",
    orgAr: "ديفيلوبر بلس",
    orgRu: "Developer Plus",
    locationEn: "North Gaza, Palestine",
    locationAr: "شمال غزة، فلسطين",
    locationRu: "Северная Газа, Палестина",
    periodEn: "07/2022 – 10/2022",
    periodAr: "07/2022 – 10/2022",
    periodRu: "07/2022 – 10/2022",
    responsibilitiesEn: [
      "Developed and tested cross-platform mobile applications using Flutter and Dart, following structured development practices.",
      "Created user interfaces and implemented application features based on project requirements.",
      "Managed project files, technical documentation, and organized development resources throughout the project lifecycle.",
      "Collaborated with technical team members to identify issues, test applications, and improve overall system performance.",
    ],
    responsibilitiesAr: [
      "تطوير واختبار تطبيقات موبايل متعددة المنصات باستخدام Flutter وDart وفق ممارسات تطوير منظمة.",
      "إنشاء واجهات المستخدم وتنفيذ ميزات التطبيق بناءً على متطلبات المشروع.",
      "إدارة ملفات المشروع والتوثيق التقني وتنظيم موارد التطوير طوال دورة حياة المشروع.",
      "التعاون مع أعضاء الفريق التقني لتحديد المشكلات واختبار التطبيقات وتحسين أداء النظام.",
    ],
    responsibilitiesRu: [
      "Разработка и тестирование кроссплатформенных мобильных приложений на Flutter и Dart.",
      "Создание пользовательских интерфейсов и реализация функций приложений.",
      "Управление файлами проекта и технической документацией.",
      "Сотрудничество с командой для выявления проблем и тестирования приложений.",
    ],
    skillTagsEn: ["Flutter", "Dart", "Mobile Development", "UI Implementation", "Team Collaboration"],
    skillTagsAr: ["Flutter", "Dart", "تطوير تطبيقات الموبايل", "تنفيذ واجهات المستخدم", "العمل الجماعي"],
    skillTagsRu: ["Flutter", "Dart", "Разработка мобильных приложений", "Реализация интерфейсов", "Командная работа"],
    type: "internship",
  },
  {
    id: "shoes",
    roleEn: "Social Media Marketer",
    roleAr: "مسوّق سوشال ميديا",
    roleRu: "Маркетолог в социальных сетях",
    orgEn: "Abu Hussein Al-Natour Shoes",
    orgAr: "أبو حسين الناطور للأحذية",
    orgRu: "Abu Hussein Al-Natour Shoes",
    locationEn: "Gaza, Palestine",
    locationAr: "غزة، فلسطين",
    locationRu: "Газа, Палестина",
    periodEn: "06/2022 – 12/2022",
    periodAr: "06/2022 – 12/2022",
    periodRu: "06/2022 – 12/2022",
    responsibilitiesEn: [
      "Managed the store's Facebook and Instagram pages.",
      "Photographed products and published posts.",
      "Scheduled posts in advance to keep publishing consistent during busy periods.",
      "Responded to customer inquiries via comments and direct messages.",
    ],
    responsibilitiesAr: [
      "إدارة صفحتي فيسبوك وإنستغرام للمتجر.",
      "تصوير المنتجات ونشرها.",
      "جدولة المنشورات مسبقًا لضمان استمرارية النشر وقت الانشغال.",
      "الرد على استفسارات الزبائن عبر الرسائل والتعليقات.",
    ],
    responsibilitiesRu: [
      "Управление страницами магазина в Facebook и Instagram.",
      "Фотографирование товаров и публикация постов.",
      "Планирование публикаций заранее.",
      "Ответы на запросы клиентов через сообщения и комментарии.",
    ],
    skillTagsEn: ["Social Media Management", "Content Creation", "Customer Communication"],
    skillTagsAr: ["إدارة السوشيال ميديا", "إنشاء المحتوى", "التواصل مع العملاء"],
    skillTagsRu: ["Управление соцсетями", "Создание контента", "Общение с клиентами"],
    type: "work",
  },
  {
    id: "ummhassan",
    roleEn: "Social Media Page Manager",
    roleAr: "مسؤول صفحة سوشال ميديا",
    roleRu: "Менеджер страницы в социальных сетях",
    orgEn: "Umm Hassan Wedding Planning & Coordination",
    orgAr: "أم حسن لتنظيم وتنسيق الأفراح",
    orgRu: "Umm Hassan — организация свадеб",
    locationEn: "Gaza, Palestine",
    locationAr: "غزة، فلسطين",
    locationRu: "Газа, Палестина",
    periodEn: "08/2026 – Present",
    periodAr: "08/2026 – حتى الآن",
    periodRu: "08/2026 – по настоящее время",
    responsibilitiesEn: [
      "Publish the services offered by Umm Hassan and showcase related work (wedding halls, photography, hairstyling, and more).",
      "Communicate with customers interested in booking and connect them directly with Umm Hassan.",
    ],
    responsibilitiesAr: [
      "نشر الخدمات التي تقدمها أم حسن وعرض الأعمال المرتبطة بها (قاعات أفراح، فوتوغرافيا، كوافير، وغيرها).",
      "التواصل مع الزبائن المهتمين بالحجز وربطهم مباشرة بأم حسن.",
    ],
    responsibilitiesRu: [
      "Публикация услуг Умм Хасан и связанных работ (свадебные залы, фотография, укладки волос и др.).",
      "Связь с клиентами, заинтересованными в бронировании, и их прямая передача Умм Хасан.",
    ],
    skillTagsEn: ["Social Media Management", "Client Coordination"],
    skillTagsAr: ["إدارة السوشيال ميديا", "تنسيق مع العملاء"],
    skillTagsRu: ["Управление соцсетями", "Координация с клиентами"],
    type: "work",
  },
];

// ============================================================
// EDUCATION — verified from CV
// ============================================================
export const education = [
  {
    id: "kytc",
    degreeEn: "Diploma in E-Business Administration",
    degreeAr: "دبلوم إدارة الأعمال الإلكترونية",
    degreeRu: "Диплом по управлению электронным бизнесом",
    institutionEn: "Khan Younis Training College (KYTC) – UNRWA",
    institutionAr: "كلية خان يونس للتدريب (KYTC) – الأونروا",
    institutionRu: "Колледж профессиональной подготовки Хан-Юнис (KYTC) – ЮНРВА",
    period: "09/2020 – 06/2022",
    focusAreasEn: [
      "CRM & Data Workflows",
      "Customer Service Operations",
      "E-Business Systems & E-Commerce",
      "Digital Marketing Fundamentals",
      "Business Communication & Technical Documentation",
    ],
    focusAreasAr: [
      "CRM وسير عمل البيانات",
      "عمليات خدمة العملاء",
      "أنظمة الأعمال الإلكترونية والتجارة الإلكترونية",
      "أساسيات التسويق الرقمي",
      "التواصل التجاري والتوثيق التقني",
    ],
    focusAreasRu: [
      "CRM и рабочие процессы с данными",
      "Операции по обслуживанию клиентов",
      "Системы электронного бизнеса и электронная торговля",
      "Основы цифрового маркетинга",
      "Деловая коммуникация и техническая документация",
    ],
    status: "completed",
  },
];

// ============================================================
// PROJECTS — verified content only
// ============================================================
export const projects = [
  {
    id: "munjiz",
    nameEn: "MUNJIZ | مُنجز",
    nameAr: "مُنجز | MUNJIZ",
    nameRu: "MUNJIZ | مُنجز",
    sloganEn: "Easier Management. Faster Achievement.",
    sloganAr: "إدارة أسهل. إنجاز أسرع.",
    sloganRu: "Проще управлять. Быстрее достигать.",
    typeEn: "Independent Product — Self-Initiated",
    typeAr: "منتج مستقل — مبادرة شخصية",
    typeRu: "Независимый продукт — личная инициатива",
    roleEn: "Project Founder & Flutter Developer",
    roleAr: "صاحب المشروع ومطوّر Flutter",
    roleRu: "Основатель проекта и Flutter-разработчик",
    statusEn: "In Development (MVP phase)",
    statusAr: "قيد التطوير (مرحلة MVP)",
    statusRu: "В разработке (фаза MVP)",
    descriptionEn: "A mobile app that brings together group project management and academic task tracking into one simple, clear experience — designed and independently developed from concept to implementation using Flutter.",
    descriptionAr: "تطبيق موبايل يجمع إدارة المشاريع الجماعية ومتابعة المهام الدراسية داخل تجربة واحدة بسيطة وواضحة — مصمم ومطوّر بشكل مستقل من الفكرة إلى التنفيذ باستخدام Flutter.",
    descriptionRu: "Мобильное приложение, объединяющее управление групповыми проектами и отслеживание учебных задач в одном простом и понятном опыте — разработанное независимо от концепции до реализации с использованием Flutter.",
    problemEn: "Student information is scattered across messages, files, and notes. Tasks get lost, deadlines are forgotten, and each team member is unclear about their responsibilities or the project's progress.",
    problemAr: "تشتت معلومات الطلاب بين الرسائل والملفات والملاحظات. تضيع المهام وتُنسى المواعيد ولا يعرف كل عضو مسؤوليته أو نسبة تقدم المشروع.",
    problemRu: "Информация студентов разбросана по сообщениям, файлам и заметкам. Задачи теряются, дедлайны забываются, и каждый участник не знает своих обязанностей или прогресса проекта.",
    solutionEn: "MUNJIZ brings together the unit, members, tasks, responsibilities, priorities, deadlines, statuses, and progress into one space — turning scattered information into measurable achievement.",
    solutionAr: "مُنجز يجمع الوحدة والأعضاء والمهام والمسؤوليات والأولويات والمواعيد والحالات والتقدم في مساحة واحدة — ويحوّل المعلومات المشتتة إلى إنجاز قابل للقياس.",
    solutionRu: "MUNJIZ объединяет проект, участников, задачи, обязанности, приоритеты, дедлайны и статусы в одном пространстве — превращая разрозненную информацию в измеримые достижения.",
    outcomeEn: "An independent product currently in active development (MVP phase), designed and developed end-to-end in Flutter — going beyond simple task tracking with an \"Achievement Moment\" feature when a unit reaches completion (celebration, reflection, archiving the lesson learned), documenting the ability to build an independent product with a clear differentiator, from problem analysis to a future development roadmap.",
    outcomeAr: "منتج مستقل قيد التطوير الفعلي (مرحلة MVP) مصمم ومطوّر بشكل كامل من الفكرة حتى التنفيذ بفلاتر — يتجاوز مجرد تتبع المهام بميزة \"لحظة الإنجاز\" عند اكتمال الوحدة (احتفال، تأمل، أرشفة الدرس المستفاد)، ما يوثّق القدرة على بناء منتج مستقل بفكرة تفاضلية واضحة، من تحليل المشكلة إلى خارطة طريق تطوير مستقبلية.",
    outcomeRu: "Независимый продукт, находящийся в активной разработке (фаза MVP), полностью спроектированный и разработанный на Flutter от идеи до реализации — выходящий за рамки простого отслеживания задач благодаря функции «момент достижения» при завершении единицы (празднование, рефлексия, архивирование извлечённого урока), подтверждающий способность создавать независимый продукт с чёткой отличительной идеей — от анализа проблемы до дорожной карты будущего развития.",
    targetUsersEn: "University students working on graduation projects, group research, volunteer projects, or courses divided into chapters.",
    targetUsersAr: "طلاب الجامعات العاملون في مشاريع التخرج والأبحاث الجماعية والمشاريع التطوعية أو المواد المقسمة إلى شابترات.",
    targetUsersRu: "Студенты университетов, работающие над дипломными проектами, групповыми исследованиями, волонтёрскими проектами или курсами, разделёнными на разделы.",
    featuresEn: [
      "Project/Course Units — organize each project or subject as a clear unit",
      "Members & Roles — assign responsibilities to each team member",
      "Tasks with Priority & Deadlines — track what needs to be done and when",
      "Status Tracking — know what's started and what's completed",
      "Progress Visualization — see what's done and what remains",
      "Achievement Moment — when a unit reaches 100%, celebrate, reflect, and archive the lesson learned",
      "Offline-first — works without constant internet connection",
    ],
    featuresAr: [
      "وحدات المشروع/المادة — تنظيم كل مشروع أو مادة كوحدة واضحة",
      "الأعضاء والأدوار — تحديد المسؤوليات لكل عضو في الفريق",
      "المهام بالأولوية والمواعيد — تتبع ما يجب فعله ومتى",
      "تتبع الحالة — معرفة ما بدأ وما اكتمل",
      "عرض التقدم — رؤية ما تم وما تبقى",
      "لحظة الإنجاز — عند وصول الوحدة لـ100%: احتفال، تأمل، وأرشفة الدرس المستفاد",
      "Offline-first — يعمل دون اتصال دائم بالإنترنت",
    ],
    featuresRu: [
      "Единицы проекта/курса — организация каждого проекта как отдельной единицы",
      "Участники и роли — распределение обязанностей",
      "Задачи с приоритетами и дедлайнами",
      "Отслеживание статуса — что начато и что завершено",
      "Визуализация прогресса",
      "Момент достижения — при 100% завершении: празднование, рефлексия, архивирование урока",
      "Offline-first — работает без постоянного интернета",
    ],
    technologiesEn: ["Flutter", "Dart", "Local Storage"],
    technologiesAr: ["Flutter", "Dart", "تخزين محلي"],
    technologiesRu: ["Flutter", "Dart", "Локальное хранилище"],
    differentiatorEn: "MUNJIZ doesn't stop at task completion. When a unit reaches 100%, it transforms the project end into a moment of celebration, reflection, and learning — building a personal archive of experiences.",
    differentiatorAr: "مُنجز لا يتوقف عند إكمال المهام. عند وصول الوحدة إلى 100%، يتحول نهاية المشروع إلى لحظة احتفال وتأمل وتعلم — لبناء أرشيف شخصي من الخبرات.",
    differentiatorRu: "MUNJIZ не останавливается на выполнении задач. При достижении 100% проект превращается в момент празднования, рефлексии и обучения.",
    timeline: [
      { phaseEn: "Month 1", phaseAr: "الشهر الأول", phaseRu: "Месяц 1", descEn: "Problem analysis, target audience, MVP requirements", descAr: "تحليل المشكلة، الفئة المستهدفة، متطلبات MVP", descRu: "Анализ проблемы, целевая аудитория, требования MVP" },
      { phaseEn: "Month 2", phaseAr: "الشهر الثاني", phaseRu: "Месяц 2", descEn: "UX/UI design, data architecture, development start", descAr: "تصميم UX/UI، بنية البيانات، بداية التطوير", descRu: "Дизайн UX/UI, архитектура данных, начало разработки" },
      { phaseEn: "Month 3", phaseAr: "الشهر الثالث", phaseRu: "Месяц 3", descEn: "Complete MVP, function testing, initial version preparation", descAr: "استكمال MVP، اختبار الوظائف، تجهيز النسخة الأولية", descRu: "Завершение MVP, тестирование, подготовка первой версии" },
      { phaseEn: "Post-Launch", phaseAr: "بعد الإطالق", phaseRu: "После запуска", descEn: "User testing, feedback, UX improvements, future planning", descAr: "تجربة التطبيق، جمع الملاحظات، تحسين UX، التخطيط المستقبلي", descRu: "Тестирование, обратная связь, улучшения UX, планирование" },
    ],
    futureEn: ["Cloud Sync", "Multi-user accounts (students & teachers)", "Web Dashboard", "Advanced analytics", "AI features", "Expansion to small work teams"],
    futureAr: ["مزامنة Cloud", "حسابات متعددة (طلاب ومدرسون)", "Web Dashboard", "تقارير متقدمة", "ميزات الذكاء الاصطناعي", "التوسع لفرق العمل الصغيرة"],
    futureRu: ["Cloud Sync", "Мультипользовательские аккаунты", "Веб-дашборд", "Расширенная аналитика", "AI-функции", "Расширение для малых команд"],
    featured: true,
    priority: 1,
    coverImage: "projects/munjiz-cover.png",
    images: [
      "projects/munjiz-splash.png",
      "projects/munjiz-home.png",
      "projects/munjiz-new-project.png",
      "projects/munjiz-report.png",
      "projects/munjiz-progress.png",
      "projects/munjiz-members.png",
      "projects/munjiz-tasks.png",
      "projects/munjiz-theme.png",
    ],
  },
  {
    id: "driving-school",
    nameEn: "Driving School Management System",
    nameAr: "نظام إدارة مدرسة قيادة السيارات",
    nameRu: "Система управления автошколой",
    typeEn: "Academic Graduation Project — Team-Based",
    typeAr: "مشروع تخرج أكاديمي — عمل جماعي",
    typeRu: "Академический дипломный проект — командная работа",
    roleEn: "Team Member — Web Front-End & Mobile Development",
    roleAr: "عضو في الفريق — تطوير الواجهة الأمامية والموبايل",
    roleRu: "Член команды — фронтенд и мобильная разработка",
    period: "08/2021 – 10/2022",
    statusEn: "Completed (Graduation Project)",
    statusAr: "مكتمل (مشروع تخرج)",
    statusRu: "Завершён (дипломный проект)",
    descriptionEn: "A management system developed as a graduation project to improve operational efficiency for driving school administration — designed and built across a web component (HTML/CSS/JavaScript) and a mobile component in Flutter (Dart), within a student team.",
    descriptionAr: "نظام إدارة طُوِّر كمشروع تخرج لتحسين الكفاءة التشغيلية لإدارة مدرسة تعليم القيادة — صُمم وبُرمج عبر مكوّن ويب (HTML/CSS/JavaScript) ومكوّن موبايل بفلاتر (Flutter/Dart)، ضمن فريق طلابي.",
    descriptionRu: "Система управления, разработанная как дипломный проект для повышения операционной эффективности автошколы — спроектированная и разработанная в виде веб-компонента (HTML/CSS/JavaScript) и мобильного компонента на Flutter (Dart), в составе студенческой команды.",
    problemEn: "Driving school administration relied on manual, traditional methods for scheduling theoretical and practical lessons and tracking students and instructors, making follow-up difficult and increasing the chance of error.",
    problemAr: "إدارة مدرسة تعليم قيادة كانت تعتمد على طرق يدوية/تقليدية لجدولة الدروس النظرية والعملية وتتبع الطلاب والمدربين، ما يصعّب المتابعة ويزيد فرص الخطأ.",
    problemRu: "Администрация автошколы использовала ручные, традиционные методы для планирования теоретических и практических занятий и отслеживания студентов и инструкторов, что усложняло контроль и увеличивало вероятность ошибок.",
    solutionEn: "Built a complete management system — a web component (HTML/CSS/JavaScript) and a mobile component in Flutter — within a student team, bringing lesson scheduling, student status tracking, and instructor coordination into one place.",
    solutionAr: "بناء نظام إدارة متكامل — مكوّن ويب (HTML/CSS/JavaScript) ومكوّن موبايل بفلاتر — ضمن فريق طلابي، يجمع جدولة الدروس، تتبع حالة الطلاب، وتنسيق المدربين في مكان واحد.",
    solutionRu: "Построена комплексная система управления — веб-компонент (HTML/CSS/JavaScript) и мобильный компонент на Flutter — в составе студенческой команды, объединяющая планирование занятий, отслеживание статуса студентов и координацию инструкторов в одном месте.",
    outcomeEn: "A completed graduation project that documented the ability to collaborate as a team and analyze a multi-platform administrative system from the study phase through to implementation.",
    outcomeAr: "مشروع تخرج مكتمل وثّق القدرة على العمل الجماعي وتحليل نظام إداري متعدد المنصات من مرحلة الدراسة حتى التنفيذ.",
    outcomeRu: "Завершённый дипломный проект, подтвердивший способность работать в команде и анализировать многоплатформенную административную систему от этапа изучения до реализации.",
    technologiesEn: ["HTML", "CSS", "JavaScript", "Flutter", "Dart", "UI/UX Design"],
    technologiesAr: ["HTML", "CSS", "JavaScript", "Flutter", "Dart", "تصميم UI/UX"],
    technologiesRu: ["HTML", "CSS", "JavaScript", "Flutter", "Dart", "UI/UX дизайн"],
    githubUrl: "https://github.com/hassanalghandourabuali/Graduation-Project",
    highlightsEn: [
      "Web-based system for scheduling and record-keeping",
      "Mobile component built with Flutter for extended access",
      "Team collaboration and project coordination",
      "System analysis and requirements documentation",
    ],
    highlightsAr: [
      "نظام ويب لإدارة الجداول والسجلات",
      "مكوّن موبايل بفلاتر للوصول الموسّع",
      "التعاون ضمن الفريق وتنسيق المشروع",
      "تحليل النظام وتوثيق المتطلبات",
    ],
    highlightsRu: [
      "Веб-система для расписания и учёта",
      "Мобильный компонент на Flutter для расширенного доступа",
      "Командная работа и координация",
      "Системный анализ и документация требований",
    ],
    featured: true,
    priority: 2,
    coverImage: "projects/driving-school-cover.png",
    imagesWeb: [
      "projects/web-add-lesson.jpg",
  "projects/web-add-lesson-2.jpg",
  "projects/web-assign-student-license.jpg",
  "projects/web-assign-student-license-2.jpg",
  "projects/web-assign-student-license-3.jpg",
  "projects/web-dashboard.jpg",
  "projects/web-dashboard-2.jpg",
  "projects/web-dashboard-3.jpg",
  "projects/web-lesson.jpg",
  "projects/web-license-test-schedule.jpg",
  "projects/web-license-test-schedule-2.jpg",
  "projects/web-license-test-schedule-3.jpg",
  "projects/web-license-test.jpg",
  "projects/web-license-test-2.jpg",
  "projects/web-license-test-3.jpg",
  "projects/web-practical-group.jpg",
  "projects/web-practical-group-2.jpg",
  "projects/web-practical-group-3.jpg",
  "projects/web-theoretical-lessons.jpg",
  "projects/web-theoretical-lessons-2.jpg",
  "projects/web-theoretical-lessons-3.jpg",
    ],
    imagesMobile: [
      "projects/drawen.jpg",
  "projects/instructor-list.jpg",
  "projects/no-lecture.jpg",
  "projects/onboarding.jpg",
  "projects/profile.jpg",
  "projects/sign2.jpg",
  "projects/sign3.jpg",
  "projects/sign4.jpg",
  "projects/sign5.jpg",
  "projects/sign6.jpg",
  "projects/signs.jpg",
  "projects/splash.jpg",
  "projects/theoretical-test.jpg",
  "projects/vehicle-list.jpg",
  "projects/verification.jpg",
    ],
  },
  {
    id: "shoes-app",
    nameEn: "Momma Fashions — Shoes & Fashion App",
    nameAr: "موما فاشونز — تطبيق أزياء وأحذية",
    nameRu: "Momma Fashions — приложение для обуви и моды",
    typeEn: "Independent Mobile App — Self-Initiated",
    typeAr: "تطبيق موبايل مستقل — مبادرة شخصية",
    typeRu: "Независимое мобильное приложение — личная инициатива",
    roleEn: "Flutter Developer",
    roleAr: "مطوّر Flutter",
    roleRu: "Flutter-разработчик",
    statusEn: "Completed (UI Implementation)",
    statusAr: "مكتمل (تنفيذ واجهات)",
    statusRu: "Завершён (реализация интерфейса)",
    descriptionEn: "A fashion e-commerce mobile app UI built with Flutter, covering the full shopping flow: onboarding, sign up/sign in with OTP verification and password reset, category browsing, product details, favorites, cart with automatic tax calculation, checkout, and order tracking.",
    descriptionAr: "واجهة تطبيق تسوق أزياء متكاملة بفلاتر، تغطي رحلة المستخدم كاملة: onboarding، تسجيل دخول/إنشاء حساب مع تحقق OTP واستعادة كلمة المرور، تصفح المنتجات حسب الفئة، تفاصيل المنتج، المفضلة، سلة الشراء مع حساب ضريبة تلقائي، إتمام الشراء، وتتبع الطلبات.",
    descriptionRu: "UI мобильного приложения для покупки одежды на Flutter: онбординг, регистрация/вход с OTP-подтверждением и сбросом пароля, просмотр товаров по категориям, детали товара, избранное, корзина с автоматическим расчётом налога, оформление заказа и отслеживание заказов.",
    problemEn: "When planning a personal shopping app, the goal was to prove the ability to implement a complete shopping experience in Flutter, rather than settling for separate screens or partial exercises.",
    problemAr: "عند التخطيط لتطبيق تسوق شخصي، كان الهدف إثبات القدرة على تنفيذ تجربة تسوق كاملة بفلاتر، بدل الاكتفاء بشاشات منفصلة أو تمارين جزئية.",
    problemRu: "При планировании личного приложения для покупок целью было доказать способность реализовать полноценный опыт покупок на Flutter, а не ограничиваться отдельными экранами или частичными упражнениями.",
    solutionEn: "Designed and built the app with interfaces covering the full journey: onboarding, sign up/sign in with OTP verification and password reset, category browsing, product details, favorites, cart with automatic tax calculation, checkout, and order tracking.",
    solutionAr: "تصميم وبرمجة التطبيق بواجهات تغطي الرحلة كاملة: onboarding، تسجيل دخول وإنشاء حساب مع تحقق OTP واستعادة كلمة المرور، تصفح حسب الفئة، تفاصيل المنتج، المفضلة، سلة الشراء مع حساب ضريبة تلقائي، إتمام الشراء، وتتبع الطلبات.",
    solutionRu: "Спроектировано и разработано приложение с интерфейсами, охватывающими весь путь: онбординг, регистрация/вход с OTP-подтверждением и сбросом пароля, просмотр по категориям, детали товара, избранное, корзина с автоматическим расчётом налога, оформление заказа и отслеживание заказов.",
    outcomeEn: "A ready app UI that documents the ability to independently implement a professional, end-to-end e-commerce experience, from sign-up to order tracking.",
    outcomeAr: "واجهة تطبيق جاهزة توثّق القدرة على تنفيذ تجربة تجارة إلكترونية احترافية ومتكاملة بشكل مستقل، من التسجيل حتى تتبع الطلب.",
    outcomeRu: "Готовый UI приложения, подтверждающий способность самостоятельно реализовать профессиональный, комплексный опыт электронной коммерции — от регистрации до отслеживания заказа.",
    technologiesEn: ["Flutter", "Dart", "UI/UX Implementation"],
    technologiesAr: ["Flutter", "Dart", "تنفيذ واجهات UI/UX"],
    technologiesRu: ["Flutter", "Dart", "Реализация UI/UX"],
    githubUrl: "https://github.com/hassanalghandourabuali/Shoes-App",
    featured: false,
    priority: 3,
    coverImage: "projects/shoes-app-cover.png",
    images: [
      "projects/shoes-app-splash.png",
      "projects/shoes-app-onboarding.png",
      "projects/shoes-app-signup.png",
      "projects/shoes-app-signin.png",
      "projects/shoes-app-home.png",
      "projects/shoes-app-product-details.png",
      "projects/shoes-app-cart.png",
      "projects/shoes-app-payment.png",
      "projects/shoes-app-payment-success.png",
      "projects/shoes-app-orders-history.png",
    ],
  },
  {
    id: "ecommerce",
    nameEn: "Lailyfa Febrina — E-Commerce App",
    nameAr: "Lailyfa Febrina — تطبيق تسوق إلكتروني",
    nameRu: "Lailyfa Febrina — приложение электронной коммерции",
    typeEn: "University Academic Coursework — Individual",
    typeAr: "مهمة أكاديمية جامعية — عمل فردي",
    typeRu: "Университетское учебное задание — индивидуальная работа",
    roleEn: "Flutter Developer",
    roleAr: "مطوّر Flutter",
    roleRu: "Flutter-разработчик",
    statusEn: "Completed",
    statusAr: "مكتمل",
    statusRu: "Завершён",
    descriptionEn: "A full-featured e-commerce mobile app built with Flutter as part of the requirements of a college course, following a fixed specification standardized for all students. Covers the complete shopping journey: authentication, browsing by category, search and filtering, product details, cart, checkout with payment method selection, order tracking, favorites, and notifications.",
    descriptionAr: "تطبيق تسوق إلكتروني متكامل بُني بفلاتر كجزء من متطلبات مادة أكاديمية بالكلية، وفق مواصفات محددة موحّدة لجميع الطلاب. يغطي رحلة التسوق كاملة: تسجيل الدخول وإنشاء الحساب، تصفح حسب الفئة، البحث والفلترة، تفاصيل المنتج، السلة، إتمام الشراء واختيار طريقة الدفع، تتبع الطلبات، المفضلة، والإشعارات.",
    descriptionRu: "Полнофункциональное мобильное приложение для электронной коммерции на Flutter, разработанное в рамках требований учебного курса колледжа по единой утверждённой спецификации для всех студентов. Охватывает полный путь покупки: авторизация, просмотр по категориям, поиск и фильтрация, детали товара, корзина, оформление заказа с выбором способа оплаты, отслеживание заказов, избранное и уведомления.",
    problemEn: "E-commerce apps need to cover a complete, seamless purchase journey — from login and browsing through to payment and order tracking — without friction points that lose the user midway.",
    problemAr: "تطبيقات التسوق الإلكتروني تحتاج تغطية رحلة شراء متكاملة وسلسة — من تسجيل الدخول والتصفح حتى الدفع وتتبع الطلب — بدون نقاط احتكاك تفقد المستخدم في منتصف الرحلة.",
    problemRu: "Приложениям электронной коммерции нужно охватывать полный, непрерывный путь покупки — от входа и просмотра до оплаты и отслеживания заказа — без точек трения, теряющих пользователя посередине пути.",
    solutionEn: "Built the app in Flutter to cover the full journey: login and sign-up, category browsing, search and filtering, product details, cart, checkout with payment method selection, order tracking, favorites, and notifications.",
    solutionAr: "بناء التطبيق بفلاتر ليغطي الرحلة كاملة: تسجيل الدخول وإنشاء الحساب، تصفح حسب الفئة، بحث وفلترة، تفاصيل المنتج، سلة، إتمام الشراء مع اختيار طريقة الدفع، تتبع الطلبات، المفضلة، والإشعارات.",
    solutionRu: "Приложение построено на Flutter и охватывает весь путь: вход и регистрация, просмотр по категориям, поиск и фильтрация, детали товара, корзина, оформление заказа с выбором способа оплаты, отслеживание заказов, избранное и уведомления.",
    outcomeEn: "A complete individual implementation of a multi-feature shopping app, delivered within the requirements of an academic course to a fixed, standardized specification — documenting readiness for independent work under fixed, binding requirements.",
    outcomeAr: "تنفيذ فردي كامل لتطبيق تسوق متعدد الميزات، أُنجز ضمن متطلبات مادة أكاديمية وفق مواصفات موحّدة محددة مسبقًا — ما يوثّق الجاهزية للعمل الفردي في ظل متطلبات ثابتة ومُلزمة.",
    outcomeRu: "Полная индивидуальная реализация многофункционального приложения для покупок, выполненная в рамках требований учебного курса по фиксированной, единой для всех спецификации — что подтверждает готовность к самостоятельной работе в условиях фиксированных, обязательных требований.",
    technologiesEn: ["Flutter", "Dart", "UI/UX Implementation"],
    technologiesAr: ["Flutter", "Dart", "تنفيذ واجهات UI/UX"],
    technologiesRu: ["Flutter", "Dart", "Реализация UI/UX"],
    githubUrl: "https://github.com/hassanalghandourabuali/E-Commerce",
    featured: false,
    priority: 4,
    coverImage: "projects/ecommerce-cover.png",
    images: [
      "projects/ecommerce-login.png",
      "projects/ecommerce-register.png",
      "projects/ecommerce-home.png",
      "projects/ecommerce-categories.png",
      "projects/ecommerce-product-detail.png",
      "projects/ecommerce-search-result.png",
      "projects/ecommerce-filter.png",
      "projects/ecommerce-cart.png",
      "projects/ecommerce-payment-method.png",
      "projects/ecommerce-success.png",
      "projects/ecommerce-order-details.png",
      "projects/ecommerce-favorites.png",
    ],
  },
    {
    id: "travel",
    nameEn: "Travel App",
    nameAr: "تطبيق سفر وسياحة",
    nameRu: "Приложение для путешествий",
    typeEn: "Independent Mobile App — Self-Initiated",
    typeAr: "تطبيق موبايل مستقل — مبادرة شخصية",
    typeRu: "Независимое мобильное приложение — личная инициатива",
    roleEn: "Flutter Developer",
    roleAr: "مطوّر Flutter",
    roleRu: "Flutter-разработчик",
    statusEn: "Completed",
    statusAr: "مكتمل",
    statusRu: "Завершён",
    descriptionEn: "A travel and booking mobile app built with Flutter, covering onboarding, authentication, a home feed with hotels, restaurants, and activities, search with filtering, location browsing on a map, notifications, and in-app chat with service providers.",
    descriptionAr: "تطبيق موبايل للسفر والحجوزات بُني بفلاتر، يغطي شاشات onboarding، تسجيل الدخول، الصفحة الرئيسية بعرض الفنادق والمطاعم والأنشطة، البحث والفلترة، تصفح المواقع على الخريطة، الإشعارات، والمحادثة داخل التطبيق مع مزودي الخدمة.",
    descriptionRu: "Мобильное приложение для путешествий и бронирования на Flutter: онбординг, авторизация, главная страница с отелями, ресторанами и активностями, поиск с фильтрацией, просмотр локаций на карте, уведомления и внутренний чат с поставщиками услуг.",
    problemEn: "After the shopping app, the next goal was to test more complex features not covered before — such as maps and in-app live chat — within the context of a travel and booking app.",
    problemAr: "بعد تطبيق التسوق، كان الهدف التالي اختبار ميزات أعقد لم تُغطَّ سابقًا — مثل الخرائط والمحادثة المباشرة داخل التطبيق — ضمن سياق تطبيق سفر وحجوزات.",
    problemRu: "После приложения для покупок следующей целью было протестировать более сложные функции, не охваченные ранее, — такие как карты и живой чат внутри приложения — в контексте приложения для путешествий и бронирования.",
    solutionEn: "Built an app including onboarding, login, a home page showing hotels, restaurants, and activities, search and filtering, browsing locations on a map, notifications, and live chat with service providers.",
    solutionAr: "بناء تطبيق يشمل onboarding، تسجيل دخول، صفحة رئيسية تعرض الفنادق والمطاعم والأنشطة، بحث وفلترة، تصفح المواقع على خريطة، إشعارات، ومحادثة مباشرة مع مزودي الخدمة.",
    solutionRu: "Построено приложение, включающее онбординг, вход, главную страницу с отелями, ресторанами и активностями, поиск и фильтрацию, просмотр локаций на карте, уведомления и живой чат с поставщиками услуг.",
    outcomeEn: "Expanded the technical skill set in Flutter to include map integration and in-app chat, while diversifying the type of apps built after the e-commerce apps.",
    outcomeAr: "توسيع نطاق المهارات التقنية بفلاتر ليشمل تكامل الخرائط والمحادثة داخل التطبيق، إضافة لتنويع نوع التطبيقات المنفذة بعد تطبيقات التجارة الإلكترونية.",
    outcomeRu: "Расширен набор технических навыков на Flutter за счёт интеграции карт и чата внутри приложения, а также разнообразие типов реализованных приложений после приложений электронной коммерции.",
    technologiesEn: ["Flutter", "Dart", "UI/UX Implementation"],
    technologiesAr: ["Flutter", "Dart", "تنفيذ واجهات UI/UX"],
    technologiesRu: ["Flutter", "Dart", "Реализация UI/UX"],
    githubUrl: "https://github.com/hassanalghandourabuali/Travel-Project",
    featured: false,
    priority: 5,
    coverImage: "projects/travel-cover.png",
    images: [
      "projects/travel-splash.png",
      "projects/travel-onboarding-country.png",
      "projects/travel-onboarding-ticket.png",
      "projects/travel-onboarding-time.png",
      "projects/travel-login.png",
      "projects/travel-home.png",
      "projects/travel-search.png",
      "projects/travel-location.png",
      "projects/travel-notifications.png",
      "projects/travel-chat.png",
    ],
  },
    {
    id: "restaurant-app-design",
    nameEn: "Elate — Restaurant App UI/UX Design",
    nameAr: "Elate — تصميم واجهات تطبيق مطعم",
    nameRu: "Elate — UI/UX дизайн приложения ресторана",
    typeEn: "Independent UI/UX Design Project — Self-Initiated",
    typeAr: "مشروع تصميم UI/UX مستقل — مبادرة شخصية",
    typeRu: "Независимый UI/UX-дизайн — личная инициатива",
    roleEn: "UI/UX Designer (Adobe XD)",
    roleAr: "مصمم UI/UX (Adobe XD)",
    roleRu: "UI/UX-дизайнер (Adobe XD)",
    statusEn: "Completed (UI/UX Design Only — No Development)",
    statusAr: "مكتمل (تصميم واجهات فقط — بدون برمجة فعلية)",
    statusRu: "Завершён (только дизайн — без разработки)",
    descriptionEn: "A complete UI/UX design for a food ordering and restaurant discovery app, created with Adobe XD. Covers the full user journey: onboarding, sign up, browsing restaurants and meals, meal details with ratings, cart, checkout and payment, order tracking, and user profile.",
    descriptionAr: "تصميم واجهات متكامل لتطبيق طلب طعام واكتشاف مطاعم، أُنجز بأدوبي XD. يغطي رحلة المستخدم كاملة: onboarding، إنشاء حساب، تصفح المطاعم والوجبات، تفاصيل الوجبة مع التقييمات، السلة، إتمام الشراء والدفع، تتبع الطلب، والملف الشخصي.",
    descriptionRu: "Полный UI/UX дизайн приложения для заказа еды и поиска ресторанов, созданный в Adobe XD. Охватывает весь путь пользователя: онбординг, регистрация, просмотр ресторанов и блюд, детали блюда с рейтингами, корзина, оформление заказа и оплата, отслеживание заказа и профиль.",
    problemEn: "Alongside development, the goal was to focus on the design (UI/UX) process in isolation from technical implementation, to master design tools and thinking independently.",
    problemAr: "إلى جانب البرمجة، كان الهدف التركيز على عملية التصميم (UI/UX) بمعزل عن التنفيذ التقني، لإتقان أدوات وتفكير التصميم بشكل مستقل.",
    problemRu: "Помимо разработки, целью было сосредоточиться на процессе дизайна (UI/UX) отдельно от технической реализации, чтобы самостоятельно освоить инструменты и мышление в дизайне.",
    solutionEn: "Designed the entire app in Adobe XD, covering the journey from onboarding and sign-up, through browsing restaurants and meals and their details with ratings, to cart, payment, order tracking, and user profile.",
    solutionAr: "تصميم التطبيق بالكامل عبر Adobe XD، يغطي الرحلة من onboarding وإنشاء الحساب، مرورًا بتصفح المطاعم والوجبات وتفاصيلها مع التقييمات، وصولًا للسلة والدفع وتتبع الطلب والملف الشخصي.",
    solutionRu: "Всё приложение спроектировано в Adobe XD, охватывая путь от онбординга и регистрации, через просмотр ресторанов и блюд и их деталей с рейтингами, до корзины, оплаты, отслеживания заказа и профиля пользователя.",
    outcomeEn: "A complete design project from the first onboarding screen to the user profile, documenting the skill of designing professional interfaces in Adobe XD independent of development.",
    outcomeAr: "مشروع تصميم متكامل من أول شاشة onboarding حتى الملف الشخصي، وثّق مهارة تصميم واجهات احترافية بأدوبي XD بمعزل عن البرمجة.",
    outcomeRu: "Полный дизайн-проект от первого экрана онбординга до профиля пользователя, подтверждающий навык профессионального дизайна интерфейсов в Adobe XD отдельно от разработки.",
    technologiesEn: ["Adobe XD", "UI/UX Design"],
    technologiesAr: ["Adobe XD", "تصميم UI/UX"],
    technologiesRu: ["Adobe XD", "UI/UX дизайн"],
    githubUrl: "https://github.com/hassanalghandourabuali/UI-Ux-Design",
    featured: false,
    priority: 6,
    coverImage: "projects/restaurant-cover.png",
    images: [
      "projects/restaurant-splash.png",
      "projects/restaurant-onboarding.png",
      "projects/restaurant-signup.png",
      "projects/restaurant-home.png",
      "projects/restaurant-restaurants.png",
      "projects/restaurant-meals.png",
      "projects/restaurant-meal-details.png",
      "projects/restaurant-cart.png",
      "projects/restaurant-payment.png",
      "projects/restaurant-payment-success.png",
      "projects/restaurant-tracking.png",
      "projects/restaurant-profile.png",
    ],
  },
];

// ============================================================
// SKILLS — verified from CV and project documents
// ============================================================
export const skillGroups = [
  {
    id: "primary",
    labelEn: "Primary Technical Skills",
    labelAr: "المهارات التقنية الأساسية",
    labelRu: "Основные технические навыки",
    level: "primary",
    skills: [
      { nameEn: "Flutter", nameAr: "Flutter", nameRu: "Flutter", evidenceEn: "Developer Plus internship + MUNJIZ project", evidenceAr: "تدريب Developer Plus + مشروع مُنجز", evidenceRu: "Стажировка Developer Plus + проект MUNJIZ" },
      { nameEn: "Dart", nameAr: "Dart", nameRu: "Dart", evidenceEn: "Developer Plus internship + MUNJIZ project", evidenceAr: "تدريب Developer Plus + مشروع مُنجز", evidenceRu: "Стажировка Developer Plus + проект MUNJIZ" },
      { nameEn: "Mobile App Development", nameAr: "تطوير تطبيقات الموبايل", nameRu: "Разработка мобильных приложений", evidenceEn: "Developer Plus internship + MUNJIZ project", evidenceAr: "تدريب Developer Plus + مشروع مُنجز", evidenceRu: "Стажировка Developer Plus + проект MUNJIZ" },
      { nameEn: "UI/UX Design", nameAr: "تصميم UI/UX", nameRu: "Дизайн UI/UX", evidenceEn: "CV skills + MUNJIZ product design", evidenceAr: "مهارات السيرة الذاتية + تصميم منتج مُنجز", evidenceRu: "Навыки из резюме + дизайн продукта MUNJIZ" },
    ],
  },
  {
    id: "business",
    labelEn: "Business & Digital",
    labelAr: "الأعمال والرقمي",
    labelRu: "Бизнес и цифровое",
    level: "secondary",
    skills: [
      { nameEn: "E-Business Management", nameAr: "إدارة أعمال إلكترونية", nameRu: "Управление электронным бизнесом", evidenceEn: "KYTC diploma", evidenceAr: "دبلوم KYTC", evidenceRu: "Диплом KYTC" },
      { nameEn: "Social Media Marketing", nameAr: "التسويق عبر وسائل التواصل الاجتماعي", nameRu: "Маркетинг в социальных сетях", evidenceEn: "Abu Hussein Shoes experience + Simplilearn Digital Marketing cert + KYTC diploma", evidenceAr: "خبرة أبو حسين للأحذية + شهادة Simplilearn في التسويق الرقمي + دبلوم KYTC", evidenceRu: "Опыт Abu Hussein Shoes + сертификат Simplilearn по цифровому маркетингу + диплом KYTC" },
    ],
  },
  {
    id: "tools",
    labelEn: "Tools & Platforms",
    labelAr: "الأدوات والمنصات",
    labelRu: "Инструменты и платформы",
    level: "supporting",
    skills: [
      { nameEn: "Microsoft Excel & Office", nameAr: "Microsoft Excel & Office", nameRu: "Microsoft Excel & Office", evidenceEn: "CV skills", evidenceAr: "مهارات السيرة الذاتية", evidenceRu: "Навыки из резюме" },
      { nameEn: "Google Workspace", nameAr: "Google Workspace", nameRu: "Google Workspace", evidenceEn: "CV skills", evidenceAr: "مهارات السيرة الذاتية", evidenceRu: "Навыки из резюме" },
      { nameEn: "Canva", nameAr: "Canva", nameRu: "Canva", evidenceEn: "CV skills", evidenceAr: "مهارات السيرة الذاتية", evidenceRu: "Навыки из резюме" },
      { nameEn: "Data Entry & Management", nameAr: "إدخال وإدارة البيانات", nameRu: "Ввод и управление данными", evidenceEn: "CV skills", evidenceAr: "مهارات السيرة الذاتية", evidenceRu: "Навыки из резюме" },
    ],
  },
  {
    id: "soft",
    labelEn: "Soft Skills",
    labelAr: "المهارات الشخصية",
    labelRu: "Личные навыки",
    level: "supporting",
    skills: [
      { nameEn: "Business Communication", nameAr: "التواصل التجاري", nameRu: "Деловая коммуникация", evidenceEn: "KYTC diploma + TeraCourses cert", evidenceAr: "دبلوم KYTC + شهادة TeraCourses", evidenceRu: "Диплом KYTC + сертификат TeraCourses" },
      { nameEn: "Problem-Solving", nameAr: "حل المشكلات", nameRu: "Решение проблем", evidenceEn: "MUNJIZ project concept", evidenceAr: "فكرة مشروع مُنجز", evidenceRu: "Концепция проекта MUNJIZ" },
      { nameEn: "Team Collaboration", nameAr: "العمل الجماعي", nameRu: "Командная работа", evidenceEn: "Developer Plus internship + Driving School project", evidenceAr: "تدريب Developer Plus + مشروع مدرسة القيادة", evidenceRu: "Стажировка Developer Plus + проект автошколы" },
    ],
  },
];

// ============================================================
// CERTIFICATIONS — verified from actual certificate documents
// Ordered by priority: technical/design first, then business,
// then supporting/soft-skill certificates.
// ============================================================
export const certifications = [
  {
    id: "c8",
    nameEn: "Developing Mobile Applications for Android using Java",
    nameAr: "تطوير تطبيقات الأندرويد باستخدام Java",
    nameRu: "Разработка мобильных приложений для Android на Java",
    issuerEn: "Mahara-Tech (ITI Platform)",
    issuerAr: "منصة مهارة تك (ITI)",
    issuerRu: "Mahara-Tech (платформа ITI)",
    date: "10/2025",
    category: "technical",
    featured: true,
    url: "certificates/mobile-development.pdf",
  },
  {
    id: "c9",
    nameEn: "Learn HTML & CSS",
    nameAr: "تعلم HTML & CSS",
    nameRu: "Изучение HTML и CSS",
    issuerEn: "Mahara-Tech (ITI Platform)",
    issuerAr: "منصة مهارة تك (ITI)",
    issuerRu: "Mahara-Tech (платформа ITI)",
    date: "10/2025",
    category: "technical",
    featured: true,
    url: "certificates/css-html.pdf",
  },
  {
    id: "c10",
    nameEn: "Adobe XD",
    nameAr: "Adobe XD",
    nameRu: "Adobe XD",
    issuerEn: "TeraCourses",
    issuerAr: "TeraCourses",
    issuerRu: "TeraCourses",
    date: "10/2025",
    category: "technical",
    featured: true,
    url: "certificates/adobe-xd.pdf",
  },
  {
    id: "c1",
    nameEn: "Introduction to Digital Marketing",
    nameAr: "مقدمة في التسويق الرقمي",
    nameRu: "Введение в цифровой маркетинг",
    issuerEn: "Simplilearn",
    issuerAr: "Simplilearn",
    issuerRu: "Simplilearn",
    date: "06/2026",
    category: "marketing",
    featured: true,
    url: "certificates/digital-marketing-intro.pdf",
  },
  {
    id: "c6",
    nameEn: "Freelancing Basics",
    nameAr: "أساسيات العمل الحر",
    nameRu: "Основы фриланса",
    issuerEn: "Mahara-Tech (ITI Platform)",
    issuerAr: "منصة مهارة تك (ITI)",
    issuerRu: "Mahara-Tech (платформа ITI)",
    date: "10/2025",
    category: "digital",
    featured: true,
    url: "certificates/freelancing-basics.pdf",
  },
  {
    id: "c3",
    nameEn: "Communication Skills",
    nameAr: "مهارات التواصل",
    nameRu: "Навыки коммуникации",
    issuerEn: "TeraCourses",
    issuerAr: "TeraCourses",
    issuerRu: "TeraCourses",
    date: "10/2025",
    category: "soft-skills",
    featured: true,
    url: "certificates/effective-communication.pdf",
  },
  {
    id: "c5",
    nameEn: "English Intermediate Level",
    nameAr: "اللغة الإنجليزية - المستوى المتوسط",
    nameRu: "Английский язык — средний уровень",
    issuerEn: "TeraCourses",
    issuerAr: "TeraCourses",
    issuerRu: "TeraCourses",
    date: "10/2025",
    category: "language",
    featured: true,
    url: "certificates/english-intermediate.pdf",
  },
];

// ============================================================
// LANGUAGES — verified from CV
// ============================================================
export const languages = [
  {
    nameEn: "Arabic",
    nameAr: "العربية",
    nameRu: "Арабский",
    levelEn: "Mother Tongue",
    levelAr: "اللغة الأم",
    levelRu: "Родной язык",
  },
  {
     nameEn: "English",
  nameAr: "الإنجليزية",
  nameRu: "Английский",
  levelEn: "Upper-Intermediate (B2)",
  levelAr: "متوسط متقدم (B2)",
  levelRu: "Выше среднего (B2)",
  },
];

// ============================================================
// NAV ITEMS
// ============================================================
export const navItems = [
  { id: "hero", labelEn: "Home", labelAr: "الرئيسية", labelRu: "Главная" },
  { id: "about", labelEn: "About", labelAr: "عني", labelRu: "Обо мне" },
  { id: "experience", labelEn: "Experience", labelAr: "الخبرة", labelRu: "Опыт" },
  { id: "projects", labelEn: "Projects", labelAr: "المشاريع", labelRu: "Проекты" },
  { id: "skills", labelEn: "Skills", labelAr: "المهارات", labelRu: "Навыки" },
  { id: "education", labelEn: "Education", labelAr: "التعليم", labelRu: "Образование" },
  { id: "contact", labelEn: "Connect", labelAr: "تواصل", labelRu: "Связь" },
];