// ============================================================
// VERIFIED PORTFOLIO DATA — Hassan Mohammed Alghandour
// All content extracted from verified source documents only.
// NO fabricated information.
// ============================================================

export const personalInfo = {
  nameEn: "Hassan Alghandour",
  nameAr: "حسن محمد الغندور",
  nameRu: "Хасан Мухаммад Альгхандур",
  titleEn: "Mobile App Developer & Digital Product Builder",
  titleAr: "مطوّر تطبيقات موبايل وباني منتجات رقمية",
  titleRu: "Разработчик мобильных приложений и создатель цифровых продуктов",
  locationEn: "Gaza, Palestine",
  locationAr: "غزة، فلسطين",
  locationRu: "Газа, Палестина",
  email: "hassanalghandour2002@gmail.com",
  phone: "(+972) 592261812",
  linkedin: "https://www.linkedin.com/in/hassanalghandour/",
  github: "https://github.com/hassanalghandourabuali",
  taglineEn: "I combine Flutter development, business thinking, and digital experience to turn ideas into practical solutions.",
  taglineAr: "أجمع بين تطوير Flutter والتفكير التجاري والخبرة الرقمية لتحويل الأفكار إلى حلول عملية.",
  taglineRu: "Я сочетаю разработку на Flutter, бизнес-мышление и цифровой опыт для превращения идей в практические решения.",
};

export const summaryEn = `Electronic Business Management graduate with practical experience in customer service, sales, CRM systems, and customer data management within the telecommunications and technology sectors. Combines a strong business background with technical understanding, focusing on mobile application development using Flutter, customer experience (CX), and digital operations.`;

export const summaryAr = `خريج إدارة الأعمال الإلكترونية بخبرة عملية في خدمة العملاء والمبيعات وأنظمة CRM وإدارة بيانات العملاء في قطاعي الاتصالات والتكنولوجيا. يجمع بين خلفية أعمال قوية وفهم تقني، مع تركيز واضح على تطوير تطبيقات الموبايل باستخدام Flutter وتجربة العملاء والعمليات الرقمية.`;

export const summaryRu = `Выпускник по управлению электронным бизнесом с практическим опытом в обслуживании клиентов, продажах, CRM-системах и управлении данными клиентов в секторах телекоммуникаций и технологий. Сочетает сильную бизнес-базу с техническим пониманием, фокусируясь на разработке мобильных приложений с Flutter.`;

// ============================================================
// EXPERIENCE — verified from CV
// ============================================================
export const experiences = [
  {
    id: "jawwal",
    roleEn: "Customer Engagement & Digital Operations Assistant",
    roleAr: "مساعد تفاعل العملاء والعمليات الرقمية",
    roleRu: "Ассистент по работе с клиентами и цифровым операциям",
    orgEn: "Jawwal Telecommunications",
    orgAr: "شركة جوال للاتصالات",
    orgRu: "Jawwal Telecommunications",
    locationEn: "Gaza, Palestine",
    locationAr: "غزة، فلسطين",
    locationRu: "Газа, Палестина",
    period: "02/2026 – 05/2026",
    responsibilitiesEn: [
      "Managed daily customer interactions through direct communication, service explanation, and follow-up to ensure high customer satisfaction (handling 30+ interactions daily).",
      "Promoted telecommunications services and digital products using value-based communication.",
      "Maintained and updated customer records using CRM systems, ensuring data integrity, accuracy, and operational compliance.",
      "Assisted in activating customer accounts and guided users through digital services and platforms.",
      "Contributed to reporting and operational documentation to support team performance tracking.",
    ],
    responsibilitiesAr: [
      "إدارة التفاعلات اليومية مع العملاء من خلال التواصل المباشر وشرح الخدمات والمتابعة لضمان رضا العملاء (أكثر من 30 تفاعلاً يومياً).",
      "تعزيز خدمات الاتصالات والمنتجات الرقمية باستخدام أسلوب التواصل القائم على القيمة.",
      "الحفاظ على سجلات العملاء وتحديثها باستخدام أنظمة CRM لضمان دقة البيانات والامتثال التشغيلي.",
      "المساعدة في تفعيل حسابات العملاء وتوجيههم عبر الخدمات والمنصات الرقمية.",
      "المساهمة في التقارير والتوثيق التشغيلي لدعم تتبع أداء الفريق.",
    ],
    responsibilitiesRu: [
      "Управление ежедневными взаимодействиями с клиентами через прямую коммуникацию и сопровождение (более 30 взаимодействий ежедневно).",
      "Продвижение телекоммуникационных услуг и цифровых продуктов.",
      "Ведение и обновление записей клиентов в CRM-системах.",
      "Помощь в активации клиентских аккаунтов и навигации по цифровым сервисам.",
      "Участие в подготовке отчётов и операционной документации.",
    ],
    skillTags: ["CRM", "Customer Experience", "Digital Operations", "Data Management"],
    type: "work",
  },
  {
    id: "shoes",
    roleEn: "Social Media & Digital Marketing Coordinator",
    roleAr: "منسق وسائل التواصل الاجتماعي والتسويق الرقمي",
    roleRu: "Координатор социальных сетей и цифрового маркетинга",
    orgEn: "Abu Hussein Al-Natour Shoes",
    orgAr: "أبو حسين النتور للأحذية",
    orgRu: "Abu Hussein Al-Natour Shoes",
    locationEn: "Gaza, Palestine",
    locationAr: "غزة، فلسطين",
    locationRu: "Газа, Палестина",
    period: "06/2022 – 12/2022",
    responsibilitiesEn: [
      "Managed the official Facebook page, creating engaging content to increase brand awareness and audience interaction.",
      "Executed and monitored basic Meta advertising campaigns targeting local market audiences.",
      "Addressed customer inquiries via comments and direct messages, improving communication efficiency and customer trust.",
      "Supported online brand presence through consistent content updates and community interaction.",
    ],
    responsibilitiesAr: [
      "إدارة الصفحة الرسمية على فيسبوك وإنشاء محتوى جذاب لزيادة الوعي بالعلامة التجارية.",
      "تنفيذ ومتابعة حملات إعلانية أساسية على Meta استهدفت جمهور السوق المحلي.",
      "الرد على استفسارات العملاء عبر التعليقات والرسائل المباشرة لتحسين كفاءة التواصل وثقة العملاء.",
      "دعم الحضور الإلكتروني للعلامة التجارية من خلال تحديثات المحتوى المنتظمة.",
    ],
    responsibilitiesRu: [
      "Управление официальной страницей Facebook и создание контента для повышения узнаваемости бренда.",
      "Запуск и мониторинг базовых рекламных кампаний Meta.",
      "Ответы на запросы клиентов через комментарии и прямые сообщения.",
      "Поддержка онлайн-присутствия бренда через регулярное обновление контента.",
    ],
    skillTags: ["Digital Marketing", "Social Media", "Content Creation", "Meta Ads"],
    type: "work",
  },
  {
    id: "developerplus",
    roleEn: "Mobile Application Developer Intern",
    roleAr: "متدرب تطوير تطبيقات موبايل",
    roleRu: "Стажёр по разработке мобильных приложений",
    orgEn: "Developer Plus",
    orgAr: "ديفيلوبر بلس",
    orgRu: "Developer Plus",
    locationEn: "North Gaza, Palestine",
    locationAr: "شمال غزة، فلسطين",
    locationRu: "Северная Газа, Палестина",
    period: "07/2022 – 10/2022",
    responsibilitiesEn: [
      "Developed and tested cross-platform mobile applications using Flutter and Dart, following structured development practices.",
      "Created user interfaces and implemented application features based on project requirements.",
      "Managed project files, technical documentation, and organized development resources throughout the project lifecycle.",
      "Collaborated with technical team members to identify issues, test applications, and improve overall system performance.",
    ],
    responsibilitiesAr: [
      "تطوير واختبار تطبيقات موبايل متعددة المنصات باستخدام Flutter وDart وفق ممارسات تطوير منظمة.",
      "إنشاء واجهات المستخدم وتنفيذ ميزات التطبيق بناءً على متطلبات المشروع.",
      "إدارة ملفات المشروع والتوثيق التقني وتنظيم موارد التطوير طوال دورة حياة المشروع.",
      "التعاون مع أعضاء الفريق التقني لتحديد المشكلات واختبار التطبيقات وتحسين أداء النظام.",
    ],
    responsibilitiesRu: [
      "Разработка и тестирование кроссплатформенных мобильных приложений на Flutter и Dart.",
      "Создание пользовательских интерфейсов и реализация функций приложений.",
      "Управление файлами проекта и технической документацией.",
      "Сотрудничество с командой для выявления проблем и тестирования приложений.",
    ],
    skillTags: ["Flutter", "Dart", "Mobile Development", "UI Implementation", "Team Collaboration"],
    type: "internship",
  },
];

// ============================================================
// EDUCATION — verified from CV
// ============================================================
export const education = [
  {
    id: "kytc",
    degreeEn: "Diploma in E-Business Administration",
    degreeAr: "دبلوم إدارة الأعمال الإلكترونية",
    degreeRu: "Диплом по управлению электронным бизнесом",
    institutionEn: "Khan Younis Training College (KYTC) – UNRWA",
    institutionAr: "كلية خان يونس للتدريب (KYTC) – الأونروا",
    institutionRu: "Колледж профессиональной подготовки Хан-Юнис (KYTC) – ЮНРВА",
    period: "09/2020 – 06/2022",
    focusAreasEn: [
      "CRM & Data Workflows",
      "Customer Service Operations",
      "E-Business Systems & E-Commerce",
      "Digital Marketing Fundamentals",
      "Business Communication & Technical Documentation",
    ],
    focusAreasAr: [
      "CRM وسير عمل البيانات",
      "عمليات خدمة العملاء",
      "أنظمة الأعمال الإلكترونية والتجارة الإلكترونية",
      "أساسيات التسويق الرقمي",
      "التواصل التجاري والتوثيق التقني",
    ],
    focusAreasRu: [
      "CRM и рабочие процессы с данными",
      "Операции по обслуживанию клиентов",
      "Системы электронного бизнеса и электронная торговля",
      "Основы цифрового маркетинга",
      "Деловая коммуникация и техническая документация",
    ],
    status: "completed",
  },
];

// ============================================================
// PROJECTS — verified content only
// ============================================================
export const projects = [
  {
    id: "munjiz",
    nameEn: "MUNJIZ | مُنجز",
    nameAr: "مُنجز | MUNJIZ",
    nameRu: "MUNJIZ | مُنجز",
    sloganEn: "Easier Management. Faster Achievement.",
    sloganAr: "إدارة أسهل. إنجاز أسرع.",
    sloganRu: "Проще управлять. Быстрее достигать.",
    typeEn: "Independent Product — Self-Initiated",
    typeAr: "منتج مستقل — مبادرة شخصية",
    typeRu: "Независимый продукт — личная инициатива",
    roleEn: "Project Founder & Flutter Developer",
    roleAr: "صاحب المشروع ومطوّر Flutter",
    roleRu: "Основатель проекта и Flutter-разработчик",
    statusEn: "In Development (MVP phase)",
    statusAr: "قيد التطوير (مرحلة MVP)",
    statusRu: "В разработке (фаза MVP)",
    descriptionEn: "A mobile app that brings together group project management and academic task tracking into one simple, clear experience — designed and independently developed from concept to implementation using Flutter.",
    descriptionAr: "تطبيق موبايل يجمع إدارة المشاريع الجماعية ومتابعة المهام الدراسية داخل تجربة واحدة بسيطة وواضحة — مصمم ومطوّر بشكل مستقل من الفكرة إلى التنفيذ باستخدام Flutter.",
    descriptionRu: "Мобильное приложение, объединяющее управление групповыми проектами и отслеживание учебных задач в одном простом и понятном опыте — разработанное независимо от концепции до реализации с использованием Flutter.",
    problemEn: "Student information is scattered across messages, files, and notes. Tasks get lost, deadlines are forgotten, and each team member is unclear about their responsibilities or the project's progress.",
    problemAr: "تشتت معلومات الطلاب بين الرسائل والملفات والملاحظات. تضيع المهام وتُنسى المواعيد ولا يعرف كل عضو مسؤوليته أو نسبة تقدم المشروع.",
    problemRu: "Информация студентов разбросана по сообщениям, файлам и заметкам. Задачи теряются, дедлайны забываются, и каждый участник не знает своих обязанностей или прогресса проекта.",
    solutionEn: "MUNJIZ brings together the unit, members, tasks, responsibilities, priorities, deadlines, statuses, and progress into one space — turning scattered information into measurable achievement.",
    solutionAr: "مُنجز يجمع الوحدة والأعضاء والمهام والمسؤوليات والأولويات والمواعيد والحالات والتقدم في مساحة واحدة — ويحوّل المعلومات المشتتة إلى إنجاز قابل للقياس.",
    solutionRu: "MUNJIZ объединяет проект, участников, задачи, обязанности, приоритеты, дедлайны и статусы в одном пространстве — превращая разрозненную информацию в измеримые достижения.",
    targetUsersEn: "University students working on graduation projects, group research, volunteer projects, or courses divided into chapters.",
    targetUsersAr: "طلاب الجامعات العاملون في مشاريع التخرج والأبحاث الجماعية والمشاريع التطوعية أو المواد المقسمة إلى شابترات.",
    targetUsersRu: "Студенты университетов, работающие над дипломными проектами, групповыми исследованиями, волонтёрскими проектами или курсами, разделёнными на разделы.",
    featuresEn: [
      "Project/Course Units — organize each project or subject as a clear unit",
      "Members & Roles — assign responsibilities to each team member",
      "Tasks with Priority & Deadlines — track what needs to be done and when",
      "Status Tracking — know what's started and what's completed",
      "Progress Visualization — see what's done and what remains",
      "Achievement Moment — when a unit reaches 100%, celebrate, reflect, and archive the lesson learned",
      "Offline-first — works without constant internet connection",
    ],
    featuresAr: [
      "وحدات المشروع/المادة — تنظيم كل مشروع أو مادة كوحدة واضحة",
      "الأعضاء والأدوار — تحديد المسؤوليات لكل عضو في الفريق",
      "المهام بالأولوية والمواعيد — تتبع ما يجب فعله ومتى",
      "تتبع الحالة — معرفة ما بدأ وما اكتمل",
      "عرض التقدم — رؤية ما تم وما تبقى",
      "لحظة الإنجاز — عند وصول الوحدة لـ100%: احتفال، تأمل، وأرشفة الدرس المستفاد",
      "Offline-first — يعمل دون اتصال دائم بالإنترنت",
    ],
    featuresRu: [
      "Единицы проекта/курса — организация каждого проекта как отдельной единицы",
      "Участники и роли — распределение обязанностей",
      "Задачи с приоритетами и дедлайнами",
      "Отслеживание статуса — что начато и что завершено",
      "Визуализация прогресса",
      "Момент достижения — при 100% завершении: празднование, рефлексия, архивирование урока",
      "Offline-first — работает без постоянного интернета",
    ],
    technologies: ["Flutter", "Dart", "Local Storage"],
    differentiatorEn: "MUNJIZ doesn't stop at task completion. When a unit reaches 100%, it transforms the project end into a moment of celebration, reflection, and learning — building a personal archive of experiences.",
    differentiatorAr: "مُنجز لا يتوقف عند إكمال المهام. عند وصول الوحدة إلى 100%، يتحول نهاية المشروع إلى لحظة احتفال وتأمل وتعلم — لبناء أرشيف شخصي من الخبرات.",
    differentiatorRu: "MUNJIZ не останавливается на выполнении задач. При достижении 100% проект превращается в момент празднования, рефлексии и обучения.",
    timeline: [
      { phaseEn: "Month 1", phaseAr: "الشهر الأول", phaseRu: "Месяц 1", descEn: "Problem analysis, target audience, MVP requirements", descAr: "تحليل المشكلة، الفئة المستهدفة، متطلبات MVP", descRu: "Анализ проблемы, целевая аудитория, требования MVP" },
      { phaseEn: "Month 2", phaseAr: "الشهر الثاني", phaseRu: "Месяц 2", descEn: "UX/UI design, data architecture, development start", descAr: "تصميم UX/UI، بنية البيانات، بداية التطوير", descRu: "Дизайн UX/UI, архитектура данных, начало разработки" },
      { phaseEn: "Month 3", phaseAr: "الشهر الثالث", phaseRu: "Месяц 3", descEn: "Complete MVP, function testing, initial version preparation", descAr: "استكمال MVP، اختبار الوظائف، تجهيز النسخة الأولية", descRu: "Завершение MVP, тестирование, подготовка первой версии" },
      { phaseEn: "Post-Launch", phaseAr: "بعد الإطالق", phaseRu: "После запуска", descEn: "User testing, feedback, UX improvements, future planning", descAr: "تجربة التطبيق، جمع الملاحظات، تحسين UX، التخطيط المستقبلي", descRu: "Тестирование, обратная связь, улучшения UX, планирование" },
    ],
    futureEn: ["Cloud Sync", "Multi-user accounts (students & teachers)", "Web Dashboard", "Advanced analytics", "AI features", "Expansion to small work teams"],
    futureAr: ["مزامنة Cloud", "حسابات متعددة (طلاب ومدرسون)", "Web Dashboard", "تقارير متقدمة", "ميزات الذكاء الاصطناعي", "التوسع لفرق العمل الصغيرة"],
    futureRu: ["Cloud Sync", "Мультипользовательские аккаунты", "Веб-дашборд", "Расширенная аналитика", "AI-функции", "Расширение для малых команд"],
    featured: true,
    priority: 1,
    images: [
      "/projects/munjiz-splash.png",
      "/projects/munjiz-home.png",
      "/projects/munjiz-new-project.png",
      "/projects/munjiz-report.png",
      "/projects/munjiz-progress.png",
      "/projects/munjiz-members.png",
      "/projects/munjiz-tasks.png",
      "/projects/munjiz-theme.png",
    ],
  },
  {
    id: "driving-school",
    nameEn: "Driving School Management System",
    nameAr: "نظام إدارة مدرسة قيادة السيارات",
    nameRu: "Система управления автошколой",
    typeEn: "Academic Graduation Project — Team-Based",
    typeAr: "مشروع تخرج أكاديمي — عمل جماعي",
    typeRu: "Академический дипломный проект — командная работа",
    roleEn: "Team Member — Web Front-End & Mobile Development",
    roleAr: "عضو في الفريق — تطوير الواجهة الأمامية والموبايل",
    roleRu: "Член команды — фронтенд и мобильная разработка",
    period: "08/2021 – 10/2022",
    statusEn: "Completed (Graduation Project)",
    statusAr: "مكتمل (مشروع تخرج)",
    statusRu: "Завершён (дипломный проект)",
    descriptionEn: "A management system developed as a graduation project to improve operational efficiency for driving school administration, combining a web component and mobile component built within a student team.",
    descriptionAr: "نظام إدارة طُوِّر كمشروع تخرج لتحسين الكفاءة التشغيلية لإدارة مدرسة تعليم القيادة، يجمع بين مكوّن ويب ومكوّن موبايل بُنيا ضمن فريق طلابي.",
    descriptionRu: "Система управления, разработанная как дипломный проект для повышения операционной эффективности автошколы, включающая веб-компонент и мобильный компонент.",
    technologiesEn: ["HTML", "CSS", "JavaScript", "Data Analysis principles", "Mobile component"],
    technologiesAr: ["HTML", "CSS", "JavaScript", "مبادئ تحليل البيانات", "مكوّن موبايل"],
    technologiesRu: ["HTML", "CSS", "JavaScript", "Принципы анализа данных", "Мобильный компонент"],
    githubUrl: "https://github.com/hassanalghandourabuali/Graduation-Project",
    highlightsEn: [
      "Web-based system for scheduling and record-keeping",
      "Mobile component for extended access",
      "Team collaboration and project coordination",
      "System analysis and requirements documentation",
    ],
    highlightsAr: [
      "نظام ويب لإدارة الجداول والسجلات",
      "مكوّن موبايل للوصول الموسّع",
      "التعاون ضمن الفريق وتنسيق المشروع",
      "تحليل النظام وتوثيق المتطلبات",
    ],
    highlightsRu: [
      "Веб-система для расписания и учёта",
      "Мобильный компонент для расширенного доступа",
      "Командная работа и координация",
      "Системный анализ и документация требований",
    ],
    featured: true,
    priority: 2,
    images: [
      "/projects/driving-school-dashboard.png",
      "/projects/driving-school-license-test.png",
      "/projects/driving-school-practical-group.png",
      "/projects/driving-school-theoretical-lessons.png",
      "/projects/driving-school-add-lesson.png",
      "/projects/driving-school-assign-students.png",
      "/projects/driving-school-lesson.png",
      "/projects/driving-school-schedule.png",
    ],
  },
];

// ============================================================
// SKILLS — verified from CV and project documents
// ============================================================
export const skillGroups = [
  {
    id: "primary",
    labelEn: "Primary Technical Skills",
    labelAr: "المهارات التقنية الأساسية",
    labelRu: "Основные технические навыки",
    level: "primary",
    skills: [
      { nameEn: "Flutter", nameAr: "Flutter", nameRu: "Flutter", evidence: "Developer Plus internship + MUNJIZ project" },
      { nameEn: "Dart", nameAr: "Dart", nameRu: "Dart", evidence: "Developer Plus internship + MUNJIZ project" },
      { nameEn: "Mobile App Development", nameAr: "تطوير تطبيقات الموبايل", nameRu: "Разработка мобильных приложений", evidence: "Developer Plus internship + MUNJIZ project" },
      { nameEn: "UI/UX Design", nameAr: "تصميم UI/UX", nameRu: "Дизайн UI/UX", evidence: "CV skills + MUNJIZ product design" },
    ],
  },
  {
    id: "business",
    labelEn: "Business & Digital",
    labelAr: "الأعمال والرقمي",
    labelRu: "Бизнес и цифровое",
    level: "secondary",
    skills: [
      { nameEn: "Customer Relationship Management (CRM)", nameAr: "إدارة علاقات العملاء (CRM)", nameRu: "Управление взаимоотношениями с клиентами (CRM)", evidence: "Jawwal experience + KYTC diploma" },
      { nameEn: "Customer Experience (CX)", nameAr: "تجربة العملاء (CX)", nameRu: "Клиентский опыт (CX)", evidence: "Jawwal experience" },
      { nameEn: "Digital Marketing", nameAr: "التسويق الرقمي", nameRu: "Цифровой маркетинг", evidence: "Abu Hussein Shoes + KYTC + Simplilearn cert" },
      { nameEn: "Social Media Marketing", nameAr: "التسويق عبر وسائل التواصل", nameRu: "Маркетинг в социальных сетях", evidence: "Abu Hussein Shoes experience" },
      { nameEn: "E-Commerce & E-Business", nameAr: "التجارة الإلكترونية والأعمال الإلكترونية", nameRu: "Электронная торговля и e-бизнес", evidence: "KYTC diploma" },
      { nameEn: "Sales Operations", nameAr: "عمليات المبيعات", nameRu: "Операции продаж", evidence: "Jawwal experience" },
    ],
  },
  {
    id: "tools",
    labelEn: "Tools & Platforms",
    labelAr: "الأدوات والمنصات",
    labelRu: "Инструменты и платформы",
    level: "supporting",
    skills: [
      { nameEn: "Microsoft Excel & Office", nameAr: "Microsoft Excel & Office", nameRu: "Microsoft Excel & Office", evidence: "CV skills" },
      { nameEn: "Google Workspace", nameAr: "Google Workspace", nameRu: "Google Workspace", evidence: "CV skills" },
      { nameEn: "Canva", nameAr: "Canva", nameRu: "Canva", evidence: "CV skills" },
      { nameEn: "Data Entry & Management", nameAr: "إدخال وإدارة البيانات", nameRu: "Ввод и управление данными", evidence: "Jawwal experience" },
    ],
  },
  {
    id: "soft",
    labelEn: "Soft Skills",
    labelAr: "المهارات الشخصية",
    labelRu: "Личные навыки",
    level: "supporting",
    skills: [
      { nameEn: "Business Communication", nameAr: "التواصل التجاري", nameRu: "Деловая коммуникация", evidence: "KYTC diploma + M3aaref cert" },
      { nameEn: "Problem-Solving", nameAr: "حل المشكلات", nameRu: "Решение проблем", evidence: "MUNJIZ project concept" },
      { nameEn: "Team Collaboration", nameAr: "العمل الجماعي", nameRu: "Командная работа", evidence: "Developer Plus internship + Driving School project" },
    ],
  },
];

// ============================================================
// CERTIFICATIONS — verified from actual certificate documents
// Ordered by priority: technical/design first, then business,
// then supporting/soft-skill certificates.
// ============================================================
export const certifications = [
  {
    id: "c8",
    nameEn: "Developing Mobile Applications for Android using Java",
    nameAr: "تطوير تطبيقات الأندرويد باستخدام Java",
    nameRu: "Разработка мобильных приложений для Android на Java",
    issuerEn: "Mahara-Tech (ITI Platform)",
    issuerAr: "منصة مهارة تك (ITI)",
    issuerRu: "Mahara-Tech (платформа ITI)",
    date: "10/2025",
    category: "technical",
    featured: true,
    url: "/certificates/mobile-development.pdf",
  },
  {
    id: "c9",
    nameEn: "Learn HTML & CSS",
    nameAr: "تعلم HTML & CSS",
    nameRu: "Изучение HTML и CSS",
    issuerEn: "Mahara-Tech (ITI Platform)",
    issuerAr: "منصة مهارة تك (ITI)",
    issuerRu: "Mahara-Tech (платформа ITI)",
    date: "10/2025",
    category: "technical",
    featured: true,
    url: "/certificates/css-html.pdf",
  },
  {
    id: "c10",
    nameEn: "Adobe XD",
    nameAr: "Adobe XD",
    nameRu: "Adobe XD",
    issuerEn: "TeraCourses",
    issuerAr: "TeraCourses",
    issuerRu: "TeraCourses",
    date: "10/2025",
    category: "technical",
    featured: true,
    url: "/certificates/adobe-xd.pdf",
  },
  {
    id: "c1",
    nameEn: "Introduction to Digital Marketing",
    nameAr: "مقدمة في التسويق الرقمي",
    nameRu: "Введение в цифровой маркетинг",
    issuerEn: "Simplilearn",
    issuerAr: "Simplilearn",
    issuerRu: "Simplilearn",
    date: "06/2026",
    category: "marketing",
    featured: true,
    url: "/certificates/digital-marketing-intro.pdf",
  },
  {
    id: "c2",
    nameEn: "Marketing and Sales",
    nameAr: "التسويق والمبيعات",
    nameRu: "Маркетинг и продажи",
    issuerEn: "M3aaref Platform",
    issuerAr: "منصة معارف",
    issuerRu: "Платформа M3aaref",
    date: "10/2025",
    category: "marketing",
    featured: true,
    url: "/certificates/marketing-sales-foundations.pdf",
  },
  {
    id: "c4",
    nameEn: "ICDL Teacher",
    nameAr: "معلم ICDL",
    nameRu: "Преподаватель ICDL",
    issuerEn: "M3aaref Platform",
    issuerAr: "منصة معارف",
    issuerRu: "Платформа M3aaref",
    date: "10/2025",
    category: "technical",
    featured: false,
    url: "/certificates/icdl-teacher.pdf",
  },
  {
    id: "c6",
    nameEn: "Freelancing Basics",
    nameAr: "أساسيات العمل الحر",
    nameRu: "Основы фриланса",
    issuerEn: "Mahara-Tech (ITI Platform)",
    issuerAr: "منصة مهارة تك (ITI)",
    issuerRu: "Mahara-Tech (платформа ITI)",
    date: "10/2025",
    category: "digital",
    featured: true,
    url: "/certificates/freelancing-basics.pdf",
  },
  {
    id: "c3",
    nameEn: "Communication Skills",
    nameAr: "مهارات التواصل",
    nameRu: "Навыки коммуникации",
    issuerEn: "TeraCourses",
    issuerAr: "TeraCourses",
    issuerRu: "TeraCourses",
    date: "10/2025",
    category: "soft-skills",
    featured: true,
    url: "/certificates/effective-communication.pdf",
  },
  {
    id: "c5",
    nameEn: "English Intermediate Level",
    nameAr: "اللغة الإنجليزية - المستوى المتوسط",
    nameRu: "Английский язык — средний уровень",
    issuerEn: "TeraCourses",
    issuerAr: "TeraCourses",
    issuerRu: "TeraCourses",
    date: "10/2025",
    category: "language",
    featured: true,
    // تأكد من الاسم الفعلي لملف الـ PDF داخل مجلد certificates وحدّث المسار إذا كان مختلفاً
    url: "/certificates/english-intermediate.pdf",
  },
  {
    id: "c7",
    nameEn: "Typing Skills",
    nameAr: "مهارات الطباعة",
    nameRu: "Навыки машинописи",
    issuerEn: "The Ottoman Turkish Cultural Center",
    issuerAr: "المركز الثقافي التركي العثماني",
    issuerRu: "Османский турецкий культурный центр",
    date: "08/2020",
    category: "technical",
    featured: false,
    url: "/certificates/typing-skills.pdf",
  },
];

// ============================================================
// LANGUAGES — verified from CV
// ============================================================
export const languages = [
  {
    nameEn: "Arabic",
    nameAr: "العربية",
    nameRu: "Арабский",
    levelEn: "Mother Tongue",
    levelAr: "اللغة الأم",
    levelRu: "Родной язык",
  },
  {
    nameEn: "English",
    nameAr: "الإنجليزية",
    nameRu: "Английский",
    levelEn: "Advanced / Proficient (C1 Listening, C1 Reading, C1 Writing, B2 Speaking)",
    levelAr: "متقدم (C1 استماع وقراءة وكتابة، B2 تحدث)",
    levelRu: "Продвинутый (C1 аудирование, чтение, письмо; B2 разговорный)",
  },
];

// ============================================================
// NAV ITEMS
// ============================================================
export const navItems = [
  { id: "hero", labelEn: "Home", labelAr: "الرئيسية", labelRu: "Главная" },
  { id: "about", labelEn: "About", labelAr: "عني", labelRu: "Обо мне" },
  { id: "experience", labelEn: "Experience", labelAr: "الخبرة", labelRu: "Опыт" },
  { id: "projects", labelEn: "Projects", labelAr: "المشاريع", labelRu: "Проекты" },
  { id: "skills", labelEn: "Skills", labelAr: "المهارات", labelRu: "Навыки" },
  { id: "education", labelEn: "Education", labelAr: "التعليم", labelRu: "Образование" },
  { id: "contact", labelEn: "Connect", labelAr: "تواصل", labelRu: "Связь" },
];
